### ISSUE TITLE
Tracking issue: updates and deprecations for Neovim 0.7

### ISSUE THREAD

**Issue by clason** [nvim-treesitter/nvim-treesitter#2793]
Now that Neovim 0.7 is released, there are a number of breaking updates we should make (ideally at the same time, **April 30, 2022**):

* [x] check GH Actions (now that "stable" means 0.7; can also bump `tree-sitter` version!) #2794, #2805 #2807 
* [x] bump the minimal required version in the README (and check it, e.g. in `checkhealth`?) #2806
* [x] remove bundled compatibility functions (`vim.ui`, `vim.notify_once`, etc.) #2800 #2801 
* [x] remove all filetype detection, now that almost all of these are available upstream #2808
* [x] remove `ensure_installed='maintained'` #2809
* [x] make use of the new APIs for autocommands, Lua files in `plugin`, namespace 0 for highlight groups #2813 (porting commands and keymaps requires a separate refactor as they're exposed to plugins)
* [ ] make use of (and document) atom-style fallback captures (like `@function.superspecial`)

**Comment by clason** [comment]
Regarding Lua mappings: this is kinda blocked by the current design of how mappings are stored in the config (see https://github.com/nvim-treesitter/playground/pull/75).

I don't think we can naively translate the current code unless we change to have a table
```
["key"] = function
```
(where function is an actual Lua function, like telescope does it) rather than, as now,
```
function = "key"
```
(where function is a string).

Of course, that would need a fundamental rewrite of the module system (with downstream implications), but I think it'd be worth it.

**Comment by clason** [comment]
The last remaining point is a bigger issue that should be discussed on its own; apart from that, the migration to 0.7 features is pretty much complete.
